name: Scheduled Update

on:
  schedule:
    - cron: "0 3 * * 6"
  push:
    paths-ignore:
      - "**.md"
      - "**.yaml"
  pull_request:
  workflow_dispatch:

jobs:
  do-stuff-pretty-please:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
         
      - name: Install Docker
        id: dock
        run: curl -fsSL https://get.docker.com | sh
        
      - name: Login to image repository
        id: login
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ secrets.REGISTRY_USER }}
          password: ${{ secrets.REGISTRY_PASSWORD }}
          
      - name: Build and push
        id: push
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: |
            ghcr.io/${{ secrets.REGISTRY_USER }}/astronvim-docker:latest
          labels: maintainer=${{ secrets.REGISTRY_USER }}
